name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Erlang
        uses: erlef/setup-beam@v1
        with:
          otp-version: OTP-27.0.1
          rebar3-version: 3.23.0
      - name: Compile
        run: make compile
      - name: Run tests
        run: make test
      - name: Hex auth
        run: rebar3 hex organization auth hexpm:pevensie --key ${{ secrets.HEX_API_KEY }}
      - name: Build
        run: make build
      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            _build/default/lib/jargon/hex/jargon-${{ github.ref_name.replace('v', '') }}.tar
            _build/default/lib/jargon/hex/jargon-${{ github.ref_name.replace('v', '') }}-docs.tar
