name: Run tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp-version: [25.3.2.31, 26.2.5.2, 27.0.1]
    name: Test on OTP ${{ matrix.otp-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Erlang
        uses: erlef/setup-beam@v1
        with:
          otp-version: OTP-${{ matrix.otp-version }}
          rebar3-version: 3.23.0
      - name: Compile
        run: make compile
      - name: Run tests
        run: make test
